-- --- Le schéma, en Postgres ---------------------------------------------------
--
-- Traduction de schema.sql (SQLite) pour Supabase. Trois différences de fond, le
-- reste est de la syntaxe :
--
--   1. Les montants ne sont plus des flottants mais des décimaux exacts. En SQLite
--      un euro était un `REAL`, où 0,10 + 0,20 fait 0,30000000000000004. Sur des
--      soldes et des budgets, cette poussière finit par se voir à l'écran.
--   2. Les colonnes qui ne valaient que 0 ou 1 sont de vrais booléens.
--   3. Les tables sont déclarées dans l'ordre de leurs dépendances. SQLite acceptait
--      qu'une table cite une table pas encore créée ; Postgres refuse.
--
-- Chaque table dit à qui appartiennent ses lignes, directement ou par le compte
-- bancaire dont elles dépendent. Sans cela, aucune règle de la base ne pourrait
-- décider quoi montrer à qui.

-- Une autorisation bancaire : une banque, une session, une expiration à 90 jours. Une
-- ligne par banque ET par utilisateur — c'est ce qui permet d'en avoir plusieurs, là
-- où trois réglages uniques n'en tenaient qu'une. session_id et valid_until sont nuls
-- entre la demande et le retour de la banque.
CREATE TABLE IF NOT EXISTS bank_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  aspsp_name TEXT NOT NULL,
  aspsp_country TEXT NOT NULL,
  session_id TEXT,
  valid_until TEXT,
  -- Les uid de comptes rapportés par la banque, en JSON. Nécessaires à la toute
  -- première synchronisation, quand aucun compte n'est encore en base.
  account_uids TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
  id TEXT PRIMARY KEY,             -- Enable Banking account uid
  name TEXT NOT NULL,
  iban_masked TEXT,
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'EUR',
  last_synced TEXT,                -- ISO datetime
  custom_name TEXT,                -- alias utilisateur ; NULL = utiliser name
  -- Propriétaire du compte (user.id de Better Auth). Obligatoire : tout le budget pend
  -- au compte bancaire, donc un compte sans propriétaire, ce sont des dépenses et des
  -- opérations qui n'apparaissent chez personne et que plus rien ne peut retirer.
  -- Pas de clé étrangère : la table `user` n'est pas créée par ce schéma mais par
  -- l'outillage de Better Auth, et les bases de test n'en ont pas.
  user_id TEXT NOT NULL,
  -- Connexion bancaire qui a rapporté ce compte. Dit quelle session présenter pour le
  -- rafraîchir, et quelle banque redemander quand l'autorisation expire.
  connection_id INTEGER REFERENCES bank_connections(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id),
  name TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  -- Vestige : plus lu par aucun calcul de budget (la vérité est dans budget_amounts).
  -- Conservé parce que les INSERT existants le remplissent encore ; ne pas s'en servir.
  monthly_amount NUMERIC(14, 2),
  start_month TEXT,                -- 'YYYY-MM' : mois de départ (invisible avant)
  end_month TEXT,                  -- 'YYYY-MM' ou NULL : dernier mois (NULL = permanent)
  -- Dépense prévue ou non prévue : les deux blocs du tableau. Se fixe à la création et
  -- ne bouge plus. Le défaut range d'office les enveloppes d'avant le découpage.
  -- Porté aussi par les revenus, où rien ne le lit.
  planned BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS group_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  -- Vestige, comme groups.monthly_amount : le budget d'une ligne vit dans
  -- line_amounts. Encore lu par listGroups (affichage) et par la reprise de données.
  amount NUMERIC(14, 2) NOT NULL,
  keyword TEXT NOT NULL,
  start_month TEXT,                -- 'YYYY-MM' ou NULL : premier mois (NULL = pas de borne)
  end_month TEXT                   -- 'YYYY-MM' ou NULL : dernier mois (NULL = permanente)
);

CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,             -- Enable Banking id, ou "manual:<uuid>" pour une saisie
  account_id TEXT NOT NULL REFERENCES accounts(id),
  date TEXT NOT NULL,              -- YYYY-MM-DD
  amount NUMERIC(14, 2) NOT NULL,  -- euros signés : débit négatif, crédit positif
  label TEXT NOT NULL,             -- libellé brut de la banque, ou libellé saisi
  group_id INTEGER REFERENCES groups(id) ON DELETE SET NULL,
  line_id INTEGER REFERENCES group_lines(id) ON DELETE SET NULL,
  excluded BOOLEAN NOT NULL DEFAULT FALSE,  -- forcé « non catégorisé »
  ignored BOOLEAN NOT NULL DEFAULT FALSE,   -- non comptabilisée (invisible pour tout calcul)
  manual BOOLEAN NOT NULL DEFAULT FALSE,    -- saisie manuelle
  note TEXT,                                -- libellé de la saisie manuelle, conservé après fusion
  comment TEXT                              -- commentaire libre, affiché sous le libellé
);

-- Les rapprochements que l'utilisateur a refusés : « cette saisie et cette opération
-- ne sont pas la même ». Le propriétaire fait partie de la clé — deux personnes
-- peuvent très bien juger différemment de la même paire, et le refus de l'une ne vaut
-- pas pour l'autre.
CREATE TABLE IF NOT EXISTS reconcile_ignored (
  user_id TEXT NOT NULL,
  manual_id TEXT NOT NULL,
  synced_id TEXT NOT NULL,
  PRIMARY KEY (user_id, manual_id, synced_id)
);

-- Budgets datés : montant d'un groupe à partir d'un mois donné. SEULE source de
-- vérité du budget d'une enveloppe. Le montant en vigueur pour un mois M est celui
-- de la ligne au plus grand effective_month <= M ; sans ligne applicable, le montant
-- est 0 — on ne retombe sur AUCUN montant de base (cf. src/lib/budget-in-force.ts).
-- group_id = 0 = non catégorisés (provision) : pas de clé étrangère volontairement,
-- puisque ce groupe-là n'existe dans aucune table.
CREATE TABLE IF NOT EXISTS budget_amounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL,
  -- Compte de la provision des non catégorisés (group_id = 0), qui n'a pas de groupe
  -- pour lui en donner un. Chaîne vide pour un budget de groupe, jamais NULL : deux
  -- NULL sont tenus pour distincts dans une contrainte d'unicité.
  account_id TEXT NOT NULL DEFAULT '',
  effective_month TEXT NOT NULL,   -- YYYY-MM
  amount NUMERIC(14, 2) NOT NULL,
  -- Portée : 'ongoing' = vaut à partir de ce mois et pour les suivants ; 'once' = ne
  -- vaut que pour ce mois. Les deux peuvent coexister au même mois (relever durablement
  -- à partir de juillet ET faire une exception pour juillet), d'où la portée dans la
  -- clé d'unicité — sinon écrire l'une effacerait l'autre.
  scope TEXT NOT NULL DEFAULT 'ongoing',
  UNIQUE (group_id, account_id, effective_month, scope)
);

-- Montants datés d'une ligne de récurrent. Même règle que budget_amounts : le
-- montant en vigueur au mois M est celui de la ligne au plus grand
-- effective_month <= M. Le budget d'un récurrent est la somme de ses lignes.
-- ON DELETE CASCADE : supprimer une ligne emporte son historique.
CREATE TABLE IF NOT EXISTS line_amounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_id INTEGER NOT NULL REFERENCES group_lines(id) ON DELETE CASCADE,
  effective_month TEXT NOT NULL,   -- YYYY-MM
  amount NUMERIC(14, 2) NOT NULL,
  scope TEXT NOT NULL DEFAULT 'ongoing',
  UNIQUE (line_id, effective_month, scope)
);

-- Notifications fermées d'une croix par l'utilisateur. L'identité est celle que
-- construit overspendNotifications (« compte::cible::mois ») : on écarte par identité,
-- pas par montant, pour qu'un dépassement qui continue de grossir ne fasse pas
-- reparaître une notification déjà écartée.
CREATE TABLE IF NOT EXISTS dismissed_notifications (
  user_id TEXT NOT NULL,
  id TEXT NOT NULL,
  dismissed_at TEXT NOT NULL,  -- ISO datetime
  PRIMARY KEY (user_id, id)
);

-- --- Les index -----------------------------------------------------------------
--
-- La base locale n'en avait aucun, et elle avait raison : sur un seul utilisateur et
-- quelques milliers d'opérations, parcourir une table entière est instantané. Partagée
-- entre des centaines de personnes, la même table se reparcourt à chaque affichage.
--
-- Un seul par chemin de lecture réellement emprunté. Les budgets datés n'en ont pas :
-- leur contrainte d'unicité en tient déjà lieu.
CREATE INDEX IF NOT EXISTS accounts_user_id_idx ON accounts (user_id);
CREATE INDEX IF NOT EXISTS bank_connections_user_id_idx ON bank_connections (user_id);
CREATE INDEX IF NOT EXISTS groups_account_id_idx ON groups (account_id);
CREATE INDEX IF NOT EXISTS group_lines_group_id_idx ON group_lines (group_id);
-- Le compte ET la date ensemble : l'application ne lit jamais un compte sans borner
-- la période, ni une période sans dire quel compte.
CREATE INDEX IF NOT EXISTS transactions_account_date_idx ON transactions (account_id, date);
CREATE INDEX IF NOT EXISTS transactions_group_id_idx ON transactions (group_id);
CREATE INDEX IF NOT EXISTS transactions_line_id_idx ON transactions (line_id);

-- --- Le cloisonnement, tenu par la base ----------------------------------------
--
-- Jusqu'ici, ce qui séparait les données de deux personnes tenait entièrement dans le
-- code : chaque requête précisait de qui elle parlait. Ça marche tant que personne
-- n'oublie. Le jour où quelqu'un écrit une lecture sans le préciser, rien ne proteste —
-- la page s'affiche, simplement elle montre tout le monde.
--
-- Ces règles-ci vivent dans la base. Le serveur ne s'y connecte plus en administrateur
-- mais sous le rôle ci-dessous, qui n'a aucun privilège particulier, et il annonce à
-- chaque fois pour qui il travaille. Sans annonce, il ne voit rien.
--
-- Le rôle ne peut pas se connecter tout seul (NOLOGIN) : ce n'est pas un compte de
-- base, c'est l'habit que le serveur enfile en arrivant.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'budget_app') THEN
    CREATE ROLE budget_app NOLOGIN;
  END IF;
END
$$;

-- Le compte par lequel l'application se connecte doit avoir le droit d'enfiler cet
-- habit-là. Sans cette appartenance, le serveur ne pourrait tout simplement pas se
-- rabaisser, et travaillerait en administrateur sans que rien ne le signale.
GRANT budget_app TO CURRENT_USER;

GRANT USAGE ON SCHEMA public TO budget_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO budget_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO budget_app;

-- Qui parle. Le second argument à `true` veut dire « ne te fâche pas si personne ne
-- l'a posé » : sans annonce, la valeur est vide, et une chaîne vide n'est le
-- propriétaire de rien. C'est ce qui fait qu'un oubli ne montre rien plutôt que tout.
CREATE OR REPLACE FUNCTION app_user_id() RETURNS TEXT
  LANGUAGE sql STABLE AS $$ SELECT COALESCE(current_setting('app.user_id', true), '') $$;

ALTER TABLE accounts               ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_connections       ENABLE ROW LEVEL SECURITY;
ALTER TABLE groups                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_lines            ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions           ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_amounts         ENABLE ROW LEVEL SECURITY;
ALTER TABLE line_amounts           ENABLE ROW LEVEL SECURITY;
ALTER TABLE reconcile_ignored      ENABLE ROW LEVEL SECURITY;
ALTER TABLE dismissed_notifications ENABLE ROW LEVEL SECURITY;

-- Les deux tables qui portent le propriétaire en clair.
CREATE POLICY a_soi ON accounts               USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
CREATE POLICY a_soi ON bank_connections       USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
CREATE POLICY a_soi ON reconcile_ignored      USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
CREATE POLICY a_soi ON dismissed_notifications USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());

-- Tout le reste du budget pend à un compte bancaire : c'est par lui qu'on remonte au
-- propriétaire. Chaque règle refait le chemin en entier plutôt que de s'appuyer sur
-- celle de la table au-dessus — une règle qui en suppose une autre est une règle qu'on
-- casse sans s'en apercevoir.
CREATE POLICY a_soi ON groups
  USING (EXISTS (SELECT 1 FROM accounts a WHERE a.id = groups.account_id AND a.user_id = app_user_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM accounts a WHERE a.id = groups.account_id AND a.user_id = app_user_id()));

CREATE POLICY a_soi ON group_lines
  USING (EXISTS (
    SELECT 1 FROM groups g JOIN accounts a ON a.id = g.account_id
    WHERE g.id = group_lines.group_id AND a.user_id = app_user_id()))
  WITH CHECK (EXISTS (
    SELECT 1 FROM groups g JOIN accounts a ON a.id = g.account_id
    WHERE g.id = group_lines.group_id AND a.user_id = app_user_id()));

CREATE POLICY a_soi ON transactions
  USING (EXISTS (SELECT 1 FROM accounts a WHERE a.id = transactions.account_id AND a.user_id = app_user_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM accounts a WHERE a.id = transactions.account_id AND a.user_id = app_user_id()));

CREATE POLICY a_soi ON line_amounts
  USING (EXISTS (
    SELECT 1 FROM group_lines l JOIN groups g ON g.id = l.group_id JOIN accounts a ON a.id = g.account_id
    WHERE l.id = line_amounts.line_id AND a.user_id = app_user_id()))
  WITH CHECK (EXISTS (
    SELECT 1 FROM group_lines l JOIN groups g ON g.id = l.group_id JOIN accounts a ON a.id = g.account_id
    WHERE l.id = line_amounts.line_id AND a.user_id = app_user_id()));

-- Les budgets datés ont deux formes. Celui d'une dépense se rattache à son groupe ;
-- celui des non catégorisés (groupe 0) n'a pas de groupe et se range sous le compte
-- lui-même. Les deux chemins doivent être ouverts, et aucun autre.
CREATE POLICY a_soi ON budget_amounts
  USING (
    CASE WHEN group_id = 0
      THEN EXISTS (SELECT 1 FROM accounts a WHERE a.id = budget_amounts.account_id AND a.user_id = app_user_id())
      ELSE EXISTS (SELECT 1 FROM groups g JOIN accounts a ON a.id = g.account_id
                   WHERE g.id = budget_amounts.group_id AND a.user_id = app_user_id())
    END)
  WITH CHECK (
    CASE WHEN group_id = 0
      THEN EXISTS (SELECT 1 FROM accounts a WHERE a.id = budget_amounts.account_id AND a.user_id = app_user_id())
      ELSE EXISTS (SELECT 1 FROM groups g JOIN accounts a ON a.id = g.account_id
                   WHERE g.id = budget_amounts.group_id AND a.user_id = app_user_id())
    END);
