-- --- Le schéma, en Postgres ---------------------------------------------------
--
-- Traduction de schema.sql (SQLite) pour Supabase. Trois différences de fond, le
-- reste est de la syntaxe :
--
--   1. Les montants ne sont plus des flottants mais des décimaux exacts. En SQLite
--      un euro était un `REAL`, où 0,10 + 0,20 fait 0,30000000000000004. Sur des
--      soldes et des budgets, cette poussière finit par se voir à l'écran.
--   2. Les colonnes qui ne valaient que 0 ou 1 sont de vrais booléens.
--   3. Les tables sont déclarées dans l'ordre de leurs dépendances. SQLite acceptait
--      qu'une table cite une table pas encore créée ; Postgres refuse.
--
-- Ce qui reste à faire ailleurs : `settings`, `reconcile_ignored` et
-- `dismissed_notifications` n'ont pas de propriétaire. Aujourd'hui elles sont
-- communes à tout le monde. Leur cloisonnement est un changement de comportement,
-- avec ses propres tests — il se fait à l'étape 5, pas dans une traduction.

-- Une autorisation bancaire : une banque, une session, une expiration à 90 jours. Une
-- ligne par banque ET par utilisateur — c'est ce qui permet d'en avoir plusieurs, là
-- où trois réglages uniques n'en tenaient qu'une. session_id et valid_until sont nuls
-- entre la demande et le retour de la banque.
CREATE TABLE IF NOT EXISTS bank_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  aspsp_name TEXT NOT NULL,
  aspsp_country TEXT NOT NULL,
  session_id TEXT,
  valid_until TEXT,
  -- Les uid de comptes rapportés par la banque, en JSON. Nécessaires à la toute
  -- première synchronisation, quand aucun compte n'est encore en base.
  account_uids TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
  id TEXT PRIMARY KEY,             -- Enable Banking account uid
  name TEXT NOT NULL,
  iban_masked TEXT,
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'EUR',
  last_synced TEXT,                -- ISO datetime
  custom_name TEXT,                -- alias utilisateur ; NULL = utiliser name
  -- Propriétaire du compte (user.id de Better Auth). Pas de clé étrangère : la table
  -- `user` n'est pas créée par ce schéma mais par le CLI de Better Auth, et les bases
  -- de test n'en ont pas. Reste nullable le temps de la migration ; devient
  -- obligatoire à l'étape 5, quand le cloisonnement passe dans la base.
  user_id TEXT,
  -- Connexion bancaire qui a rapporté ce compte. Dit quelle session présenter pour le
  -- rafraîchir, et quelle banque redemander quand l'autorisation expire.
  connection_id INTEGER REFERENCES bank_connections(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id TEXT NOT NULL REFERENCES accounts(id),
  name TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  -- Vestige : plus lu par aucun calcul de budget (la vérité est dans budget_amounts).
  -- Conservé parce que les INSERT existants le remplissent encore ; ne pas s'en servir.
  monthly_amount NUMERIC(14, 2),
  start_month TEXT,                -- 'YYYY-MM' : mois de départ (invisible avant)
  end_month TEXT,                  -- 'YYYY-MM' ou NULL : dernier mois (NULL = permanent)
  -- Dépense prévue ou non prévue : les deux blocs du tableau. Se fixe à la création et
  -- ne bouge plus. Le défaut range d'office les enveloppes d'avant le découpage.
  -- Porté aussi par les revenus, où rien ne le lit.
  planned BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS group_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  -- Vestige, comme groups.monthly_amount : le budget d'une ligne vit dans
  -- line_amounts. Encore lu par listGroups (affichage) et par la reprise de données.
  amount NUMERIC(14, 2) NOT NULL,
  keyword TEXT NOT NULL,
  start_month TEXT,                -- 'YYYY-MM' ou NULL : premier mois (NULL = pas de borne)
  end_month TEXT                   -- 'YYYY-MM' ou NULL : dernier mois (NULL = permanente)
);

CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,             -- Enable Banking id, ou "manual:<uuid>" pour une saisie
  account_id TEXT NOT NULL REFERENCES accounts(id),
  date TEXT NOT NULL,              -- YYYY-MM-DD
  amount NUMERIC(14, 2) NOT NULL,  -- euros signés : débit négatif, crédit positif
  label TEXT NOT NULL,             -- libellé brut de la banque, ou libellé saisi
  group_id INTEGER REFERENCES groups(id) ON DELETE SET NULL,
  line_id INTEGER REFERENCES group_lines(id) ON DELETE SET NULL,
  excluded BOOLEAN NOT NULL DEFAULT FALSE,  -- forcé « non catégorisé »
  ignored BOOLEAN NOT NULL DEFAULT FALSE,   -- non comptabilisée (invisible pour tout calcul)
  manual BOOLEAN NOT NULL DEFAULT FALSE,    -- saisie manuelle
  note TEXT,                                -- libellé de la saisie manuelle, conservé après fusion
  comment TEXT                              -- commentaire libre, affiché sous le libellé
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS reconcile_ignored (
  manual_id TEXT NOT NULL,
  synced_id TEXT NOT NULL,
  PRIMARY KEY (manual_id, synced_id)
);

-- Budgets datés : montant d'un groupe à partir d'un mois donné. SEULE source de
-- vérité du budget d'une enveloppe. Le montant en vigueur pour un mois M est celui
-- de la ligne au plus grand effective_month <= M ; sans ligne applicable, le montant
-- est 0 — on ne retombe sur AUCUN montant de base (cf. src/lib/budget-in-force.ts).
-- group_id = 0 = non catégorisés (provision) : pas de clé étrangère volontairement,
-- puisque ce groupe-là n'existe dans aucune table.
CREATE TABLE IF NOT EXISTS budget_amounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL,
  -- Compte de la provision des non catégorisés (group_id = 0), qui n'a pas de groupe
  -- pour lui en donner un. Chaîne vide pour un budget de groupe, jamais NULL : deux
  -- NULL sont tenus pour distincts dans une contrainte d'unicité.
  account_id TEXT NOT NULL DEFAULT '',
  effective_month TEXT NOT NULL,   -- YYYY-MM
  amount NUMERIC(14, 2) NOT NULL,
  -- Portée : 'ongoing' = vaut à partir de ce mois et pour les suivants ; 'once' = ne
  -- vaut que pour ce mois. Les deux peuvent coexister au même mois (relever durablement
  -- à partir de juillet ET faire une exception pour juillet), d'où la portée dans la
  -- clé d'unicité — sinon écrire l'une effacerait l'autre.
  scope TEXT NOT NULL DEFAULT 'ongoing',
  UNIQUE (group_id, account_id, effective_month, scope)
);

-- Montants datés d'une ligne de récurrent. Même règle que budget_amounts : le
-- montant en vigueur au mois M est celui de la ligne au plus grand
-- effective_month <= M. Le budget d'un récurrent est la somme de ses lignes.
-- ON DELETE CASCADE : supprimer une ligne emporte son historique.
CREATE TABLE IF NOT EXISTS line_amounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_id INTEGER NOT NULL REFERENCES group_lines(id) ON DELETE CASCADE,
  effective_month TEXT NOT NULL,   -- YYYY-MM
  amount NUMERIC(14, 2) NOT NULL,
  scope TEXT NOT NULL DEFAULT 'ongoing',
  UNIQUE (line_id, effective_month, scope)
);

-- Notifications fermées d'une croix par l'utilisateur. L'identité est celle que
-- construit overspendNotifications (« compte::cible::mois ») : on écarte par identité,
-- pas par montant, pour qu'un dépassement qui continue de grossir ne fasse pas
-- reparaître une notification déjà écartée.
CREATE TABLE IF NOT EXISTS dismissed_notifications (
  id TEXT PRIMARY KEY,
  dismissed_at TEXT NOT NULL   -- ISO datetime
);

-- --- Les index -----------------------------------------------------------------
--
-- La base locale n'en avait aucun, et elle avait raison : sur un seul utilisateur et
-- quelques milliers d'opérations, parcourir une table entière est instantané. Partagée
-- entre des centaines de personnes, la même table se reparcourt à chaque affichage.
--
-- Un seul par chemin de lecture réellement emprunté. Les budgets datés n'en ont pas :
-- leur contrainte d'unicité en tient déjà lieu.
CREATE INDEX IF NOT EXISTS accounts_user_id_idx ON accounts (user_id);
CREATE INDEX IF NOT EXISTS bank_connections_user_id_idx ON bank_connections (user_id);
CREATE INDEX IF NOT EXISTS groups_account_id_idx ON groups (account_id);
CREATE INDEX IF NOT EXISTS group_lines_group_id_idx ON group_lines (group_id);
-- Le compte ET la date ensemble : l'application ne lit jamais un compte sans borner
-- la période, ni une période sans dire quel compte.
CREATE INDEX IF NOT EXISTS transactions_account_date_idx ON transactions (account_id, date);
CREATE INDEX IF NOT EXISTS transactions_group_id_idx ON transactions (group_id);
CREATE INDEX IF NOT EXISTS transactions_line_id_idx ON transactions (line_id);
